spring:
  application:
    name: dept-server
  profile: prod

eureka:
  #在启动时指定
  #client:
  #serviceUrl:
  #defaultZone: http://peer1:8001/eureka,http:peer2:8002/eureka
  instance:
    instance-id: service-provider
    prefer-ip-address: true
