spring:
  application:
    name: dept-server
  profile: prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: service-provider
    prefer-ip-address: true
