server:
  port: 2300
spring:
  application:
    name: zuul
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka,http://peer2:1002/eureka

# 路由的作用:
# 当A服务有一个 add 接口，B服务也有一个 add接口，此时可以通过路由来区分
zuul:
  ignored-services: he**
  ignored-patterns: /a
  add-host-header: true
  retryable: true
  #prefix: /pre
  routes:
    hello-service:
      path: /hello/**
      serviceId: consumer-ribbon
# 快捷设置
#zuul:
#  routes:
#    hello-service:/hello/**
#zuul:
#  routes:
#    hello-service
#spring security
security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:2301/uaa/oauth/token #token 端点
      user-authorization-uri: http://localhost:2301/uaa/oauth/authorize #授权端点
      client-id: zuul #oAuth2 客户端ID
      client-secret: secret #oAuth2 客户端密钥
    resource:
      jwt:
        key-value: msa123456 #使用对称加密方式，加密方式为HS256
