server:
  port: 8989
management:
  security:
    enabled: false
    endpoints:
      web:
        exposure:
          include: hystrix.stream
spring:
  application:
    name: turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/

turbine:
  app-config: consumer-ribbon
  cluster-name-expression: default
  combine-host-port: true

feign:
  hystrix:
    enable: true