server:
  port: 8989
management:
  port: 8990
spring:
  application:
    name: turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/

turbine:
  app-config: consumer-ribbon
  cluster-name-expression: default
  combine-host-port: true