server:
  port: 1111

spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 1001
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://peer2:1002/eureka/
---
server:
  port: 1002
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://peer1:1001/eureka/